version: "3.6"
services:
  web:
    build: ./web/
    environment:
     - FLASK_ENV=development
    ports:
     - 8008:8008

  jupyter:
    build: ./jupyter/
    volumes:
      - ./notebooks:/home/jovyan
      - ./dataset:/home/jovyan/dataset
    ports:
      - 8888:8888
    container_name:   jupyter_notebook
    command: "start-notebook.sh"
